### PR TITLE
Upgrade to Ansible version 1.9.4.

### PR DESCRIPTION
**Pull request by smarnach**
JIRA ticket: [OSPR-1169](https://openedx.atlassian.net/browse/OSPR-1169)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @smarnach! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=19&repo=edx%2Fedx-analytics-configuration

**Comment by mtyaka** [comment]
:+1:

**Comment by edx-webhook** [comment]
Thanks for the pull request, @smarnach! I've created [OSPR-1169](https://openedx.atlassian.net/browse/OSPR-1169) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-analytics-configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by bradenmacdonald** [comment]
This was supposed to be for OLIVE-18 rather than an OSPR. Sorry for the noise.

@mulby could you please review?

See also https://github.com/edx/edx-analytics-pipeline/pull/209

**Comment by edx-webhook** [comment]
Hello @smarnach: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Comment by smarnach** [comment]
I closed the OSPR ticket (since I thought it's not needed anymore), which resulted in this PR being closed, and for some reason I don't understand the usual "Reopen" button is gone, so I'm forced to open a new PR.

**Pull request closed without merging**
